### PR TITLE
Fix/move icp tests to separate folder

### PR DESCRIPTION
**Pull request by YoshuaNava**
## Description

This PR separates the main file for libpointmatcher's unit tests (`utest.cpp`), from the existing ICP tests. The motivation being that, I have more ICP tests in implementation stage, and I see the potential to cover more facets of the algorithm.

## Tests

All succeeding locally.

### Instructions
I tested this locally with a ROS1 catkin build, by 

1. Cloning libpointmatcher into a catkin workspace, along with the latest version of [libnabo](https://github.com/ethz-asl/libnabo)
2. Building with `catkin build -DBUILD_TESTS=Enabled`
3. Executing the tests from the catkin workspace folder with `$ ./build/libpointmatcher/utest/utest --path <path_to_workspace>/src/libpointmatcher/examples/data/`

### CODE REVIEW

**Comment by pomerlef** [comment]
Add to whitelist

**Comment by YoshuaNava** [comment]
Hi @pomerlef,
There is a message saying that all checks have failed, but no tests were run:

image

What could be the issue? I also see it in https://github.com/ethz-asl/libpointmatcher/pull/508

**Comment by YoshuaNava** [comment]
Hi @pomerlef,
Sorry to bother. I wanted to catch up on the status of this MR, and your thoughts on it.

Thank you in advance :pray:

**Comment by YoshuaNava** [comment]
Thank you!

About the pipeline, it doesn't seem to be running atm:

image


Is there any way I could trigger it?

**Comment by pomerlef** [comment]
The CI tool setup by ASL seems out of order. I need to set up a local machine to validate the modification. Once it is done, I'll start processing the PRs.

**Comment by YoshuaNava** [comment]
Oki. No prob.

**Comment by pomerlef** [comment]
This was manually merged into `master`.

**Pull request closed without merging**
