### PR TITLE
Add missing force4DOF param to PointToPlaneWithCov

### PR DESCRIPTION
**Pull request by bhavitp**
#378 added a `force4DOF` param to PointToPlane error minimizer. This param also needs to be added to PointToPlaneWithCov.

### CODE REVIEW

**Comment by harleypritchard** [comment]
I have tested and can confirm that this fix resolves errors running PointToPlaneWithCov.

**Comment by rgreid** [comment]
Hi admins /@pomerlef can you please merge this one-line PR?   We can confirm it builds and performs correctly.  `libpointmatcher` crashes using the `force4DOF` option without it.

**Comment by pomerlef** [comment]
ok to test

**Comment by pomerlef** [comment]
@rgreid thanks for reminding me and @bhavitp for fixing the problem! The PR would have stay pending forever otherwise...

**Comment by bhavitp** [comment]
Not a problem. Thank you @rgreid and @harleypritchard for reminding the admins of this PR

**Pull request merged**
