### PR TITLE
handle reflexion in PointToPointWithCovErrorMinimizer

### PR DESCRIPTION
**Pull request by artivis**
Answering issue #215 .

### CODE REVIEW

**Comment by pomerlef** [comment]
ok to test

**Comment by pomerlef** [comment]
@HannesSommer the error seems to be related to the system installation:
```
CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:nabo>

  No target "nabo"
```

**Comment by HannesSommer** [comment]
@pomerlef , that's a bit of a nasty one. `cmake` is finding random (old) versions of `libnaboConfig.cmake` on Jenkins. I'm on it.

**Comment by HannesSommer** [comment]
Okay, PR #218 should solve the build issue discovered here together with the Jenkins changes I already applied.

**Comment by pomerlef** [comment]
Awesome, thanks a lot, @HannesSommer. Do we need to wait for the PR in libnabo to be accepted too?

**Comment by HannesSommer** [comment]
No, this works without that PR for libnabo, because it is now finding properly the installed (vs. build) version of the `libnaboConfig.cmake` file. That PR is for the build version, which libpointmatcher was using before (most of the times).

**Pull request merged**
