### PR TITLE
Search for pthread or pthreadVC2 lib in CMakeLists

### PR DESCRIPTION
**Pull request by maximecharriere**
Following [issue 421](https://github.com/ethz-asl/libpointmatcher/issues/421)

pthread is a POSIX library. So Windows can't compile project that include `pthread.h`.
Windows use threads included in `windows.h`.
To use pthread, Windows users have to get [pthreads-win32](https://sourceware.org/pthreads-win32/).
The library provided by pthreads-win32 is called `pthreadVC2.lib`.
So CMake have to search for pthread and pthreadVC2

I'm new to GitHub and CMake, tell me if I'm doing something wrong.

### CODE REVIEW

**Comment by pomerlef** [comment]
ok to test

**Comment by pomerlef** [comment]
@peci1 will it break something on your side?

**Comment by peci1** [comment]
Looking through the repo, I'm not even sure pthread is really needed. I only see usages of boost::thread. But I'm not sure if boost pulls in pthread automatically or not. But definitely, boost::thread should not rely on pthread on windows.

The standard way of getting pthread is `find_package(Threads)` and then linking against `Threads::Threads` imported target. This should correctly handle all operating systems and pull in their respective threading dependencies. But the imported target is only available since CMake 3.1. As libpointmatcher tries to support 2.8, it should instead use variable `CMAKE_THREAD_LIBS_INIT` when linking targets that require threading support.

So, I'd suggests something like

    find_package(Threads REQUIRED)
    if (CMAKE_VERSION VERSION_LESS 3.1.0)
      set(EXTERNAL_LIBS ${EXTERNAL_LIBS} ${CMAKE_THREAD_LIBS_INIT})
    else()
      set(EXTERNAL_LIBS ${EXTERNAL_LIBS} Threads::Threads)
    endif()

**Comment by pomerlef** [comment]
Is that PR still valid or #437 has priority on that one?

**Comment by maximecharriere** [comment]
#437 is a nicer solution because the user doesn't have to download pthread

**Pull request closed without merging**
