### PR TITLE
Create LICENSE file based on BSD license as per package.xml

### PR DESCRIPTION
**Pull request by Timple**
Same as https://github.com/ethz-asl/libnabo/pull/118

### CODE REVIEW

**Comment by pomerlef** [comment]
There is a duplicate commit from #482. Please update the PR.

**Comment by Timple** [comment]
I was under the assumption these commits dropped out upon merging the other PR.

But I updated the PR to a single commit :+1:

**Comment by stephanemagnenat** [comment]
The license is wrong, the copyright is clearly not 2021 ASL, as Libpointmatcher was created far earlier and people from other institutions have also contributed. The best would be a date range and something like "the Libpointmatcher authors" regarding who owns the copyright.

**Review by pomerlef — APPROVED** [review]

**Comment by pomerlef** [comment]
I'm fine with the changes, but the branch is still out-of-date with master

**Comment by Timple** [comment]
Out of date how?

It only contains the three commits for the license. Or would you like me to rebase onto master?

**Comment by pomerlef** [comment]
ok to test

**Pull request merged**
