### PR TITLE
Support multiple build systems such as pure make, catkin, ament, etc

### PR DESCRIPTION
**Pull request by YoshuaNava**
This PR introduces new cmake files that allow libpointmatcher to be built natively with ROS catkin, or to rather be built as it has been, with a pure cmake setup that works on Windows, Mac OS or Linux.

I created new cmake files with the config needed, and additionally enabled the unit tests on the ROS side. With this new config it would also be possible to build and release a libpointmatcher ROS package.

All feedback is warmly welcome. I will try to tag all regulars users of libpointmatcher that I know of.

### CODE REVIEW

**Comment by YoshuaNava** [comment]
@AlexandreG87 After the Python bindings are merged, could you help me to adapt the changes in this MR? To provide support for them with catkin and cmake builds.

**Comment by AlexandreG87** [comment]
> @AlexandreG87 After the Python bindings are merged, could you help me to adapt the changes in this MR? To provide support for them with catkin and cmake builds.

@YoshuaNava Yes, I can help you.

**Comment by YoshuaNava** [comment]
@AlexandreG87 Thanks a lot :slightly_smiling_face:

**Comment by YoshuaNava** [comment]
@peci1 I have addressed most of the comments on the libnabo PR here as well.

**Comment by pomerlef** [comment]
@YoshuaNava is this PR still relevant?

**Comment by YoshuaNava** [comment]
@pomerlef I think it would be very nice to have this change, but the changes needed have accumulated. I would prefer to close the current PR and open a new one in the future, with more organization from my side (e.g. a table where we list small PRs with minimal and better scoped changes).

(This also applies to the mirror on the libnabo repo)

**Comment by pomerlef** [comment]
alright, I'm closing it!

**Pull request closed without merging**
