### PR TITLE
catkin not required for pure cmake packages

### PR DESCRIPTION
**Pull request by Timple**
This prevens rosdep resolving in ROS2

### CODE REVIEW

**Comment by pomerlef** [comment]
ok to test

**Comment by pomerlef** [comment]
@simonpierredeschenes can you check if this patch will break default ROS1 installs ?

**Comment by simonpierredeschenes** [comment]
I'll have a look

**Comment by Timple** [comment]
For what it's worth: it has beendone before for pure cmake packages :slightly_smiling_face: 
https://github.com/nobleo/paho.mqtt.c-release/blob/master/patches/package.xml

**Pull request merged**
