### PR TITLE
Add yaml file testing point-to-point icp

### PR DESCRIPTION
**Pull request by oleg-alexandrov**
There are a lot of yaml files that are used in unit tests, but none test point-to-point icp, they are all for point-to-plane. I added one, to make the test sequence more complete.

### CODE REVIEW

**Comment by oleg-alexandrov** [comment]
I have no idea why the test failed. It worked for me. This is a trivial commit and whatever problem happened, should be easy to fix. I don't have access to the log above to see the problem.

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
The error message was 
```
/var/lib/jenkins/jobs/libpointmatcher/workspace/utest/utest.cpp:147
Expected: (transErr) < (transTol), actual: 0.144691 vs 0.1
This error was caused by the test file:
   ../examples/data/icp_data/defaultPointToPointMinDistDataPointsFilter.yaml
```
I let it rerun. But the result is the same. It does not seem to be random and unlikely. It doesn't fail on your computer?

**Comment by oleg-alexandrov** [comment]
I related a bit the translation check. Now it passes.

**Comment by pomerlef** [comment]
thanks Oleg

**Pull request merged**
